### ISSUE TITLE
.angular-cli.json styles references incorrect style location for bootstrap

### ISSUE THREAD

**Issue by steve-nickerson** [Jflima92/angular-cli-issue-5739#1]
When creating a new project with the cli the .angular-cli.json file's style section has a typo.

node_modules should be the correct folder name, not node-modules   - vs. _

Actual:
```
 "styles": [
        "styles.css",
        "../node-modules/bootstrap/dist/css/bootstrap.min.css"
      ],
```

Expected:
```
 "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
```

if this is not automatically generated by the cli then please disregard.

**Comment by jfmlima** [comment]
Hi @steve-nickerson, it is not automatically generated by the angular-cli. 
This repo was used to replicate an issue on the official [angular-cli](https://github.com/angular/angular-cli) repository so I will close this issue.
